DROP INDEX "shipping_companies_name_key";
CREATE UNIQUE INDEX "shipping_companies_organization_id_name_key" ON "shipping_companies"("organization_id", "name");
DROP INDEX "supplier_invoices_supplier_name_supplier_invoice_no_key";
CREATE UNIQUE INDEX "supplier_invoices_org_supplier_number_key" ON "supplier_invoices"("organization_id", "supplier_name", "supplier_invoice_no");
ALTER TABLE "supplier_invoices" ADD COLUMN "intake_request_key" TEXT, ADD COLUMN "intake_fingerprint" TEXT, ADD COLUMN "review_note" TEXT, ADD COLUMN "is_final_invoice" BOOLEAN NOT NULL DEFAULT false, ADD COLUMN "source_document_id" TEXT;
CREATE UNIQUE INDEX "supplier_invoices_organization_id_intake_request_key_key" ON "supplier_invoices"("organization_id", "intake_request_key");
ALTER TABLE "order_margin_snapshots" ADD COLUMN "calculation_basis" JSONB, ADD COLUMN "input_fingerprint" TEXT, ADD COLUMN "cost_review_note" TEXT, ADD COLUMN "costs_reviewed_at" TIMESTAMP(3);
ALTER TABLE "finance_exceptions" ADD COLUMN "rule_key" TEXT, ADD COLUMN "source_fingerprint" TEXT, ADD COLUMN "last_detected_at" TIMESTAMP(3);
CREATE UNIQUE INDEX "finance_exceptions_organization_id_rule_key_key" ON "finance_exceptions"("organization_id", "rule_key");
ALTER TABLE "accounting_export_batches" ADD COLUMN "legal_entity_id" TEXT, ADD COLUMN "period_from" TIMESTAMP(3), ADD COLUMN "period_to" TIMESTAMP(3), ADD COLUMN "request_key" TEXT, ADD COLUMN "source_fingerprint" TEXT, ADD COLUMN "prepared_csv" TEXT;
CREATE UNIQUE INDEX "accounting_export_batches_organization_id_request_key_key" ON "accounting_export_batches"("organization_id", "request_key");
ALTER TYPE "FinanceExceptionType" ADD VALUE 'OrderCostIncomplete';
ALTER TYPE "FinanceAuditAction" ADD VALUE 'SupplierInvoiceCreated';
ALTER TYPE "FinanceAuditAction" ADD VALUE 'SupplierInvoiceEdited';
ALTER TYPE "FinanceAuditAction" ADD VALUE 'SupplierEvidenceAttached';
ALTER TYPE "FinanceAuditAction" ADD VALUE 'AccountingExportCreated';
ALTER TYPE "FinanceAuditAction" ADD VALUE 'MarginCalculated';
ALTER TYPE "FinanceAuditAction" ADD VALUE 'MarginCostsReviewed';
ALTER TYPE "FinanceAuditAction" ADD VALUE 'FinanceChecksCompleted';
