export const ERP_LIFECYCLE_STATUSES = {
  DRAFT: "Draft",
  OPEN: "Open",
  PENDING_REVIEW: "PendingReview",
  PENDING_APPROVAL: "PendingApproval",
  REVIEWED: "Reviewed",
  APPROVED: "Approved",
  REJECTED: "Rejected",
  ACTIVE: "Active",
  IN_PROGRESS: "InProgress",
  AWAITING_APPROVAL: "AwaitingApproval",
  BLOCKED: "Blocked",
  ESCALATED: "Escalated",
  RESOLVED: "Resolved",
  DISMISSED: "Dismissed",
  ARCHIVED: "Archived",
  CANCELLED: "Cancelled",
  COMPLETED: "Completed",
  POSTED: "Posted",
  READY: "Ready",
  DISPATCHED: "Dispatched",
  DELIVERED: "Delivered",
  CONFIRMED: "Confirmed",
  IN_FULFILLMENT: "InFulfillment",
  PARTIALLY_DELIVERED: "PartiallyDelivered",
  SENT: "Sent",
  PARTIALLY_RESPONDED: "PartiallyResponded",
  RESPONDED: "Responded",
  CLOSED: "Closed",
  ACCEPTED: "Accepted",
  DECLINED: "Declined",
  EXPIRED: "Expired",
  FAILED: "Failed",
} as const;

export type ErpLifecycleStatus = (typeof ERP_LIFECYCLE_STATUSES)[keyof typeof ERP_LIFECYCLE_STATUSES] | string;

export interface LifecycleDefinition {
  initial: ErpLifecycleStatus;
  terminal: ErpLifecycleStatus[];
  transitions: Record<string, ErpLifecycleStatus[]>;
}

export const STANDARD_REVIEW_LIFECYCLE: LifecycleDefinition = {
  initial: ERP_LIFECYCLE_STATUSES.DRAFT,
  terminal: [
    ERP_LIFECYCLE_STATUSES.APPROVED,
    ERP_LIFECYCLE_STATUSES.REJECTED,
    ERP_LIFECYCLE_STATUSES.ARCHIVED,
    ERP_LIFECYCLE_STATUSES.CANCELLED,
  ],
  transitions: {
    [ERP_LIFECYCLE_STATUSES.DRAFT]: [ERP_LIFECYCLE_STATUSES.PENDING_REVIEW, ERP_LIFECYCLE_STATUSES.CANCELLED],
    [ERP_LIFECYCLE_STATUSES.PENDING_REVIEW]: [ERP_LIFECYCLE_STATUSES.REVIEWED, ERP_LIFECYCLE_STATUSES.APPROVED, ERP_LIFECYCLE_STATUSES.REJECTED, ERP_LIFECYCLE_STATUSES.BLOCKED],
    [ERP_LIFECYCLE_STATUSES.REVIEWED]: [ERP_LIFECYCLE_STATUSES.APPROVED, ERP_LIFECYCLE_STATUSES.REJECTED, ERP_LIFECYCLE_STATUSES.BLOCKED],
    [ERP_LIFECYCLE_STATUSES.BLOCKED]: [ERP_LIFECYCLE_STATUSES.PENDING_REVIEW, ERP_LIFECYCLE_STATUSES.REJECTED, ERP_LIFECYCLE_STATUSES.CANCELLED],
    [ERP_LIFECYCLE_STATUSES.APPROVED]: [ERP_LIFECYCLE_STATUSES.ACTIVE, ERP_LIFECYCLE_STATUSES.ARCHIVED],
    [ERP_LIFECYCLE_STATUSES.ACTIVE]: [ERP_LIFECYCLE_STATUSES.ARCHIVED, ERP_LIFECYCLE_STATUSES.CANCELLED],
  },
};

export const STANDARD_EXCEPTION_LIFECYCLE: LifecycleDefinition = {
  initial: ERP_LIFECYCLE_STATUSES.OPEN,
  terminal: [ERP_LIFECYCLE_STATUSES.RESOLVED, ERP_LIFECYCLE_STATUSES.DISMISSED],
  transitions: {
    [ERP_LIFECYCLE_STATUSES.OPEN]: [ERP_LIFECYCLE_STATUSES.PENDING_REVIEW, ERP_LIFECYCLE_STATUSES.ESCALATED, ERP_LIFECYCLE_STATUSES.RESOLVED, ERP_LIFECYCLE_STATUSES.DISMISSED],
    [ERP_LIFECYCLE_STATUSES.PENDING_REVIEW]: [ERP_LIFECYCLE_STATUSES.OPEN, ERP_LIFECYCLE_STATUSES.ESCALATED, ERP_LIFECYCLE_STATUSES.RESOLVED, ERP_LIFECYCLE_STATUSES.DISMISSED],
    [ERP_LIFECYCLE_STATUSES.ESCALATED]: [ERP_LIFECYCLE_STATUSES.PENDING_REVIEW, ERP_LIFECYCLE_STATUSES.RESOLVED, ERP_LIFECYCLE_STATUSES.DISMISSED],
    [ERP_LIFECYCLE_STATUSES.RESOLVED]: [ERP_LIFECYCLE_STATUSES.OPEN],
    [ERP_LIFECYCLE_STATUSES.DISMISSED]: [ERP_LIFECYCLE_STATUSES.OPEN],
  },
};

export const BACKORDER_LIFECYCLE: LifecycleDefinition = {
  initial: ERP_LIFECYCLE_STATUSES.OPEN,
  terminal: [ERP_LIFECYCLE_STATUSES.RESOLVED, ERP_LIFECYCLE_STATUSES.DISMISSED],
  transitions: {
    [ERP_LIFECYCLE_STATUSES.OPEN]: [
      ERP_LIFECYCLE_STATUSES.ESCALATED,
      ERP_LIFECYCLE_STATUSES.RESOLVED,
      ERP_LIFECYCLE_STATUSES.DISMISSED,
    ],
    [ERP_LIFECYCLE_STATUSES.ESCALATED]: [
      ERP_LIFECYCLE_STATUSES.RESOLVED,
      ERP_LIFECYCLE_STATUSES.DISMISSED,
    ],
    [ERP_LIFECYCLE_STATUSES.RESOLVED]: [ERP_LIFECYCLE_STATUSES.OPEN],
    [ERP_LIFECYCLE_STATUSES.DISMISSED]: [ERP_LIFECYCLE_STATUSES.OPEN],
  },
};

export const GOODS_RECEIPT_LIFECYCLE: LifecycleDefinition = {
  initial: ERP_LIFECYCLE_STATUSES.DRAFT,
  terminal: [ERP_LIFECYCLE_STATUSES.POSTED, ERP_LIFECYCLE_STATUSES.CANCELLED],
  transitions: {
    [ERP_LIFECYCLE_STATUSES.DRAFT]: [ERP_LIFECYCLE_STATUSES.POSTED, ERP_LIFECYCLE_STATUSES.CANCELLED],
  },
};

export const DELIVERY_LIFECYCLE: LifecycleDefinition = {
  initial: ERP_LIFECYCLE_STATUSES.DRAFT,
  terminal: [ERP_LIFECYCLE_STATUSES.DELIVERED, ERP_LIFECYCLE_STATUSES.CANCELLED],
  transitions: {
    [ERP_LIFECYCLE_STATUSES.DRAFT]: [ERP_LIFECYCLE_STATUSES.READY, ERP_LIFECYCLE_STATUSES.CANCELLED],
    [ERP_LIFECYCLE_STATUSES.READY]: [ERP_LIFECYCLE_STATUSES.DISPATCHED, ERP_LIFECYCLE_STATUSES.CANCELLED],
    [ERP_LIFECYCLE_STATUSES.DISPATCHED]: [ERP_LIFECYCLE_STATUSES.DELIVERED],
  },
};

export const SUPPLIER_INQUIRY_LIFECYCLE: LifecycleDefinition = {
  initial: ERP_LIFECYCLE_STATUSES.DRAFT,
  terminal: [ERP_LIFECYCLE_STATUSES.CLOSED, ERP_LIFECYCLE_STATUSES.CANCELLED],
  transitions: {
    [ERP_LIFECYCLE_STATUSES.DRAFT]: [ERP_LIFECYCLE_STATUSES.SENT, ERP_LIFECYCLE_STATUSES.CANCELLED],
    [ERP_LIFECYCLE_STATUSES.SENT]: [ERP_LIFECYCLE_STATUSES.PARTIALLY_RESPONDED, ERP_LIFECYCLE_STATUSES.RESPONDED, ERP_LIFECYCLE_STATUSES.CLOSED],
    [ERP_LIFECYCLE_STATUSES.PARTIALLY_RESPONDED]: [ERP_LIFECYCLE_STATUSES.RESPONDED, ERP_LIFECYCLE_STATUSES.CLOSED],
    [ERP_LIFECYCLE_STATUSES.RESPONDED]: [ERP_LIFECYCLE_STATUSES.CLOSED],
  },
};

export const CUSTOMER_QUOTE_LIFECYCLE: LifecycleDefinition = {
  initial: ERP_LIFECYCLE_STATUSES.DRAFT,
  terminal: [
    ERP_LIFECYCLE_STATUSES.ACCEPTED,
    ERP_LIFECYCLE_STATUSES.DECLINED,
    ERP_LIFECYCLE_STATUSES.EXPIRED,
    ERP_LIFECYCLE_STATUSES.CANCELLED,
  ],
  transitions: {
    [ERP_LIFECYCLE_STATUSES.DRAFT]: [ERP_LIFECYCLE_STATUSES.PENDING_APPROVAL, ERP_LIFECYCLE_STATUSES.CANCELLED],
    [ERP_LIFECYCLE_STATUSES.PENDING_APPROVAL]: [ERP_LIFECYCLE_STATUSES.APPROVED, ERP_LIFECYCLE_STATUSES.DRAFT, ERP_LIFECYCLE_STATUSES.CANCELLED],
    [ERP_LIFECYCLE_STATUSES.APPROVED]: [ERP_LIFECYCLE_STATUSES.SENT, ERP_LIFECYCLE_STATUSES.CANCELLED],
    [ERP_LIFECYCLE_STATUSES.SENT]: [
      ERP_LIFECYCLE_STATUSES.ACCEPTED,
      ERP_LIFECYCLE_STATUSES.DECLINED,
      ERP_LIFECYCLE_STATUSES.EXPIRED,
      ERP_LIFECYCLE_STATUSES.CANCELLED,
    ],
  },
};

export const SALES_ORDER_LIFECYCLE: LifecycleDefinition = {
  initial: ERP_LIFECYCLE_STATUSES.CONFIRMED,
  terminal: [ERP_LIFECYCLE_STATUSES.DELIVERED, ERP_LIFECYCLE_STATUSES.CANCELLED],
  transitions: {
    [ERP_LIFECYCLE_STATUSES.CONFIRMED]: [
      ERP_LIFECYCLE_STATUSES.IN_FULFILLMENT,
      ERP_LIFECYCLE_STATUSES.PARTIALLY_DELIVERED,
      ERP_LIFECYCLE_STATUSES.DELIVERED,
      ERP_LIFECYCLE_STATUSES.CANCELLED,
    ],
    [ERP_LIFECYCLE_STATUSES.IN_FULFILLMENT]: [
      ERP_LIFECYCLE_STATUSES.PARTIALLY_DELIVERED,
      ERP_LIFECYCLE_STATUSES.DELIVERED,
      ERP_LIFECYCLE_STATUSES.CANCELLED,
    ],
    [ERP_LIFECYCLE_STATUSES.PARTIALLY_DELIVERED]: [ERP_LIFECYCLE_STATUSES.DELIVERED],
  },
};

export function canTransitionStatus(definition: LifecycleDefinition, from: ErpLifecycleStatus, to: ErpLifecycleStatus) {
  if (from === to) return true;
  return (definition.transitions[from] ?? []).includes(to);
}

export function assertTransitionStatus(definition: LifecycleDefinition, from: ErpLifecycleStatus, to: ErpLifecycleStatus) {
  if (!canTransitionStatus(definition, from, to)) {
    throw new Error(`Invalid lifecycle transition from ${from} to ${to}.`);
  }
}
