"use client";
import { useCallback, useEffect, useRef, useState } from "react";
import type { AgentAction } from "@/lib/agents/capabilities";
type Schedule = { id: string; agentId: string; action: string; intervalMinutes: number; maxDailyRuns: number; enabled: boolean; revision: number; nextRunAt: string; leaseUntil: string | null; lastError: string | null; lastRunId: string | null };
const button = "rounded-md border border-primary/25 px-3 py-2 text-sm text-primary disabled:opacity-40";
export function AgentSchedules({ agentId, action, inputs, canManage }: { agentId: string; action?: AgentAction; inputs: Record<string, string>; canManage: boolean }) {
  const [rows, setRows] = useState<Schedule[]>([]), [worker, setWorker] = useState(false), [minutes, setMinutes] = useState(60), [limit, setLimit] = useState(8), [allowProvider, setAllowProvider] = useState(false), [busy, setBusy] = useState(false), [message, setMessage] = useState("");
  const requestKey = useRef("");
  const load = useCallback(async () => { const response = await fetch("/api/v1/agents/schedules", { cache: "no-store" }); const result = await response.json(); if (!response.ok || !result.ok) throw new Error(result.error?.message || "Could not load schedules."); setRows(result.data.schedules); setWorker(result.data.workerEnabled); }, []);
  useEffect(() => { const refresh = () => void load().catch(error => setMessage(error.message)); refresh(); const timer = setInterval(refresh, 5000); return () => clearInterval(timer); }, [load]);
  useEffect(() => { requestKey.current = ""; setAllowProvider(false); }, [agentId, action?.action, inputs]);
  async function save(row?: Schedule) {
    setBusy(true); setMessage("");
    try {
      requestKey.current ||= crypto.randomUUID();
      const response = await fetch("/api/v1/agents/schedules", { method: row ? "PATCH" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(row ? { id: row.id, enabled: !row.enabled, revision: row.revision } : { agentId, action: action?.action, params: inputs, intervalMinutes: minutes, maxDailyRuns: limit, allowProvider, requestKey: requestKey.current }) });
      const result = await response.json(); if (!response.ok || !result.ok) throw new Error(result.error?.message || "Schedule change failed.");
      requestKey.current = ""; await load(); setMessage(row ? "Schedule updated." : "Schedule created. Results appear in recent runs and require review.");
    } catch (error) { setMessage(error instanceof Error ? error.message : "Schedule change failed."); }
    finally { setBusy(false); }
  }
  return <section aria-label="Agent schedules" className="my-4 space-y-3 border-t border-outline-variant/20 pt-4 text-sm"><h4 className="font-semibold">Schedules</h4><p className="text-outline">Runs while the Nautex backend is available. Closing the standalone app stops the worker. Missed intervals are combined into one run; failed runs retry at most twice.</p>{!worker && <p className="text-warning">The schedule worker is not enabled in this runtime.</p>}{canManage && action && <div className="space-y-3"><p>Schedule <strong>{action.label}</strong> using the execution inputs in this panel.</p><div className="flex flex-wrap gap-3"><label>Interval (minutes)<input type="number" min={5} max={10080} value={minutes} onChange={event => { setMinutes(Number(event.target.value)); requestKey.current = ""; }} className="ml-2 w-24 rounded bg-surface-base p-2" /></label><label>Maximum runs per UTC day<input type="number" min={1} max={96} value={limit} onChange={event => { setLimit(Number(event.target.value)); requestKey.current = ""; }} className="ml-2 w-20 rounded bg-surface-base p-2" /></label></div>{["provider", "hybrid"].includes(action.mode) && <label className="flex items-start gap-2"><input type="checkbox" checked={allowProvider} onChange={event => { setAllowProvider(event.target.checked); requestKey.current = ""; }} />Allow provider usage for this schedule. Runs may incur charges; the run limit is not a currency budget.</label>}<button className={button} disabled={busy || (["provider", "hybrid"].includes(action.mode) && !allowProvider)} onClick={() => void save()}>Create schedule</button></div>}{rows.filter(row => row.agentId === agentId).map(row => <div key={row.id} className="rounded border border-outline-variant/20 p-3"><p>{row.action.replaceAll("_", " ")} · {row.enabled ? "Enabled" : "Paused"}{row.leaseUntil ? " · Run claimed" : ""}</p><p className="text-outline">Every {row.intervalMinutes} min · limit {row.maxDailyRuns}/day · next {new Date(row.nextRunAt).toLocaleString()}</p>{row.lastError && <p className="text-warning">{row.lastError}</p>}{canManage && <button className={`${button} mt-2`} disabled={busy} onClick={() => void save(row)}>{row.enabled ? "Pause and cancel active run" : "Resume"}</button>}</div>)}{message && <p role="status">{message}</p>}</section>;
}
