"use client";

import { useCallback, useEffect, useState } from "react";
import { money } from "@/lib/finance/calculations";

const field = "rounded-lg border border-outline-variant/30 bg-surface-container px-3 py-2 text-sm text-on-surface";
const button = "rounded-lg bg-primary/15 px-3 py-2 text-sm font-semibold text-primary disabled:opacity-40";
const panel = "space-y-4 rounded-xl border border-outline-variant/20 bg-surface-container-low p-5";
type Movement = { id: string; amount: string; currency: string; paidAt: string; reference: string; recordedBy: string; reversedAt: string | null; reversalReason: string | null };
type Supplier = { id: string; supplierInvoiceNo: string; supplierName: string; currency: string; approvalStatus: string; legalEntityId: string | null; grossAmount: number; paidAmount: number; outstandingAmount: number; payments: Movement[] };
type Credit = { id: string; creditNoteNo: string; currency: string; grossAmount: string; refundOutstanding: number; appliedToInvoiceAt: string | null; originalInvoice: { invoiceNo: string; grossAmount: string; paidAmount: string; creditedAmount: string; outstandingAmount: string; updatedAt: string }; refunds: Movement[] };
type Ledger = { canManage: boolean; suppliers: Supplier[]; credits: Credit[]; legalEntities: { id: string; name: string }[]; invoices: { id: string; invoiceNo: string; currency: string; grossAmount: string; creditedAmount: string }[] };
type Draft = { action: string; id: string; kind?: string; title: string; max?: number; currency?: string; invoiceVersion?: string; balance?: string; requestKey: string };
async function read<T>(url: string, init?: RequestInit): Promise<T> { const response = await fetch(url, init); const result = await response.json(); if (!response.ok || result.ok === false) throw new Error(result.error?.message ?? "The request could not be completed."); return result.data; }

export function FinanceSettlements({ onChanged }: { onChanged: () => unknown }) {
  const [data, setData] = useState<Ledger | null>(null), [error, setError] = useState(""), [notice, setNotice] = useState(""), [busy, setBusy] = useState(false);
  const [draft, setDraft] = useState<Draft | null>(null);
  const load = useCallback(async () => { try { setData(await read<Ledger>("/api/v1/finance/settlements")); } catch (e) { setError((e as Error).message); } }, []);
  useEffect(() => { void load(); }, [load]);
  function start(input: Omit<Draft, "requestKey">) { setDraft({ ...input, requestKey: crypto.randomUUID() }); setError(""); setNotice(""); }
  async function submit(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault(); if (!draft || busy) return;
    const values = Object.fromEntries(new FormData(event.currentTarget)); setBusy(true); setError("");
    try {
      await read("/api/v1/finance/settlements", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...draft, ...values, ...(values.amount ? { amount: Number(values.amount) } : {}), ...(values.grossAmount ? { grossAmount: Number(values.grossAmount), vatAmount: Number(values.vatAmount) } : {}) }) });
      setDraft(null); setNotice(draft.action === "draft_credit" ? "Credit drafted. Review, approve and issue it in Credit Notes." : "Review saved. Balances and audit history refreshed."); await load(); await onChanged();
    } catch (e) { setError((e as Error).message); } finally { setBusy(false); }
  }
  return <div className="space-y-5">
    <section className={panel}><h2 className="text-lg font-semibold">Payments & Reconciliation</h2><p className="text-sm text-on-surface-variant">Record payments and refunds already made, with the bank or source reference. These controls do not send money. Reversing a record corrects this ledger and preserves its history.</p>
      {error && <p role="alert" className="text-error">{error}</p>}{notice && <p role="status" className="text-success">{notice}</p>}
      {!data ? <p>Loading settlement records…</p> : !data.canManage ? <p>Finance reviewer permission is required to change these records.</p> : <button className={button} onClick={() => start({ action: "draft_credit", id: "", title: "Draft customer credit" })}>Draft customer credit</button>}
      {draft && <form key={draft.requestKey} onSubmit={submit} className="space-y-4 rounded-lg border border-primary/30 p-4">
        <h3 className="font-semibold">{draft.title}</h3>{draft.balance && <p className="text-sm">{draft.balance}</p>}
        <div className="flex flex-wrap items-end gap-4">
          {draft.action === "draft_credit" && <><label className="grid gap-1 text-sm">Original invoice<select name="id" required className={field}><option value="">Choose posted invoice</option>{data?.invoices.map(row => <option key={row.id} value={row.id}>{row.invoiceNo} · remaining {money(Number(row.grossAmount) - Number(row.creditedAmount), row.currency)}</option>)}</select></label><label className="grid gap-1 text-sm">Credit gross<input name="grossAmount" type="number" step="0.01" min="0.01" required className={field} /></label><label className="grid gap-1 text-sm">Recorded VAT<input name="vatAmount" type="number" step="0.01" min="0" required className={field} /></label></>}
          {draft.action === "record" && <><label className="grid gap-1 text-sm">Amount ({draft.currency})<input name="amount" type="number" step="0.01" min="0.01" max={draft.max} required className={field} /></label><label className="grid gap-1 text-sm">Payment date<input name="paidAt" type="date" max={new Date().toISOString().slice(0, 10)} required className={field} /></label></>}
          {draft.action === "assign_entity" && <label className="grid gap-1 text-sm">Legal entity<select name="legalEntityId" required className={field}><option value="">Choose entity</option>{data?.legalEntities.map(row => <option key={row.id} value={row.id}>{row.name}</option>)}</select></label>}
          {draft.action === "reconcile" && <label className="grid gap-1 text-sm">Verified treatment<select name="method" required className={field}><option value="">Choose after reviewing statements</option><option value="apply_now">Credit has not reduced the balance: apply now</option><option value="already_reflected">Credit already reduced the balance: record its allocation</option></select></label>}
          <label className="grid min-w-64 flex-1 gap-1 text-sm">{draft.action === "record" ? "Bank / payment reference" : "Supporting review reason"}<input name={draft.action === "record" ? "reference" : "reason"} minLength={5} maxLength={1000} required className={field} /></label>
        </div><div className="flex gap-3"><button disabled={busy} className={button}>{busy ? "Saving…" : "Confirm and save"}</button><button type="button" disabled={busy} className={button} onClick={() => setDraft(null)}>Cancel</button></div>
      </form>}
    </section>
    <section className={panel}><h3 className="font-semibold">Supplier payments</h3><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr>{["Invoice / supplier", "Approval / entity", "Gross", "Recorded paid", "Outstanding", "Actions"].map(label => <th className="p-3" key={label}>{label}</th>)}</tr></thead><tbody>{data?.suppliers.map(row => <tr key={row.id} className="border-t border-outline-variant/15"><td className="p-3">{row.supplierInvoiceNo}<div className="text-on-surface-variant">{row.supplierName}</div></td><td className="p-3">{row.approvalStatus}<div>{data.legalEntities.find(entity => entity.id === row.legalEntityId)?.name ?? "Entity requires review"}</div></td><td className="p-3">{money(row.grossAmount, row.currency)}</td><td className="p-3">{money(row.paidAmount, row.currency)}</td><td className="p-3">{money(row.outstandingAmount, row.currency)}</td><td className="space-x-2 p-3"><button className={button} disabled={!data.canManage || row.approvalStatus !== "Approved" || row.outstandingAmount <= 0} onClick={() => start({ action: "record", kind: "supplier_payment", id: row.id, title: `Record payment · ${row.supplierInvoiceNo}`, max: row.outstandingAmount, currency: row.currency })}>Record payment</button><button className={button} disabled={!data.canManage} onClick={() => start({ action: "assign_entity", id: row.id, title: `Review legal entity · ${row.supplierInvoiceNo}` })}>Assign entity</button></td></tr>)}</tbody></table></div>{data && !data.suppliers.length && <p>No supplier invoices in this organization.</p>}</section>
    <section className={panel}><h3 className="font-semibold">Issued credits and customer refunds</h3><p className="text-sm text-on-surface-variant">Historical credits require a source-backed review before changing balances. Ambiguous allocations are rejected. Refunds become available when a reconciled credit exceeds the unpaid invoice balance.</p>{data?.credits.map(row => <div key={row.id} className="flex flex-wrap items-center justify-between gap-3 border-t border-outline-variant/15 py-3"><div>{row.creditNoteNo} · {row.originalInvoice.invoiceNo}<div className="text-sm text-on-surface-variant">Credit {money(Number(row.grossAmount), row.currency)} · refund due {money(row.refundOutstanding, row.currency)} · {row.appliedToInvoiceAt ? "Allocated" : "Historical allocation needs review"}</div></div>{row.appliedToInvoiceAt ? <button className={button} disabled={!data.canManage || row.refundOutstanding <= 0} onClick={() => start({ action: "record", kind: "customer_refund", id: row.id, title: `Record refund · ${row.creditNoteNo}`, max: row.refundOutstanding, currency: row.currency })}>Record refund</button> : <button className={button} disabled={!data.canManage} onClick={() => start({ action: "reconcile", id: row.id, title: `Review historical credit · ${row.creditNoteNo}`, invoiceVersion: row.originalInvoice.updatedAt, balance: `Invoice gross ${money(Number(row.originalInvoice.grossAmount), row.currency)}, paid ${money(Number(row.originalInvoice.paidAmount), row.currency)}, credited ${money(Number(row.originalInvoice.creditedAmount), row.currency)}, outstanding ${money(Number(row.originalInvoice.outstandingAmount), row.currency)}.` })}>Review allocation</button>}</div>)}{data && !data.credits.length && <p>No issued credit notes.</p>}</section>
    <section className={panel}><h3 className="font-semibold">Settlement history</h3>{data && [...data.suppliers.flatMap(row => row.payments.map(payment => ({ ...payment, kind: "supplier_payment", parent: row.supplierInvoiceNo }))), ...data.credits.flatMap(row => row.refunds.map(refund => ({ ...refund, kind: "customer_refund", parent: row.creditNoteNo })))].map(row => <div key={row.id} className="flex flex-wrap items-center justify-between gap-3 border-t border-outline-variant/15 py-3"><div>{row.parent} · {money(Number(row.amount), row.currency)} · {row.paidAt.slice(0, 10)}<div className="text-sm text-on-surface-variant">{row.reference} · recorded by {row.recordedBy}{row.reversedAt && ` · Reversed: ${row.reversalReason}`}</div></div><button className={button} disabled={!data.canManage || !!row.reversedAt} onClick={() => start({ action: "reverse", kind: row.kind, id: row.id, title: `Reverse ledger entry · ${row.parent}` })}>Reverse entry</button></div>)}</section>
  </div>;
}

type VatData = { basis: string; rulesVersion: string; excludedCount: number; legalEntities: { id: string; name: string }[]; groups: { legalEntity: string; currency: string; salesVat: number; creditVat: number; purchaseVat: number; recordedDifference: number; records: number }[]; rows: { id: string; kind: string; reference: string; date: string | null; legalEntity: string; currency: string; net: number; vat: number; gross: number; included: boolean; exclusion: string | null }[] };
export function VatReview() {
  const today = new Date().toISOString().slice(0, 10);
  const [from, setFrom] = useState(`${today.slice(0, 7)}-01`), [to, setTo] = useState(today), [entity, setEntity] = useState(""), [data, setData] = useState<VatData | null>(null), [error, setError] = useState(""), [busy, setBusy] = useState(false), [loadedQuery, setLoadedQuery] = useState("");
  async function load(event: React.FormEvent) { event.preventDefault(); setBusy(true); setError(""); setData(null); const query = new URLSearchParams({ from, to, ...(entity ? { legalEntityId: entity } : {}) }).toString(); try { setData(await read<VatData>(`/api/v1/finance/vat-review?${query}`)); setLoadedQuery(query); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }
  async function download() { try { const response = await fetch(`/api/v1/finance/vat-review?${loadedQuery}&format=csv`); if (!response.ok) throw new Error("Export failed. Reload the review and try again."); const url = URL.createObjectURL(await response.blob()), link = document.createElement("a"); link.href = url; link.download = "nautex-vat-review.csv"; link.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); } catch (e) { setError((e as Error).message); } }
  return <section className={panel}><h2 className="text-lg font-semibold">VAT Review</h2><p className="text-sm text-on-surface-variant">Internal review of recorded VAT by period. This report does not determine tax liability, deductibility or statutory filing amounts.</p><form onSubmit={load} className="flex flex-wrap items-end gap-3"><label className="grid gap-1 text-sm">From<input className={field} type="date" value={from} onChange={e => setFrom(e.target.value)} required /></label><label className="grid gap-1 text-sm">To<input className={field} type="date" value={to} onChange={e => setTo(e.target.value)} required /></label><label className="grid gap-1 text-sm">Legal entity<select className={field} value={entity} onChange={e => setEntity(e.target.value)}><option value="">All entities, separately</option>{data?.legalEntities.map(row => <option key={row.id} value={row.id}>{row.name}</option>)}</select></label><button className={button} disabled={busy}>{busy ? "Loading…" : "Load period"}</button></form>{error && <p role="alert" className="text-error">{error}</p>}{data && <><p className="text-sm">{data.basis}</p><p className="text-sm">{data.excludedCount} excluded documents · basis {data.rulesVersion}</p><button className={button} onClick={() => void download()}>Export reviewed period CSV</button><div className="grid gap-4 md:grid-cols-2">{data.groups.map(row => <div key={`${row.legalEntity}:${row.currency}`} className="rounded-lg border border-outline-variant/20 p-4"><h3 className="font-semibold">{row.legalEntity} · {row.currency}</h3><p>Sales VAT: {money(row.salesVat, row.currency)}</p><p>Credit VAT: {money(row.creditVat, row.currency)}</p><p>Purchase VAT: {money(row.purchaseVat, row.currency)}</p><p className="font-semibold">Recorded difference: {money(row.recordedDifference, row.currency)}</p><p className="text-sm">{row.records} documents</p></div>)}</div><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr>{["Source", "Date", "Entity", "Net", "VAT", "Gross", "Review status"].map(label => <th className="p-3" key={label}>{label}</th>)}</tr></thead><tbody>{data.rows.map(row => <tr key={`${row.kind}:${row.id}`} className="border-t border-outline-variant/15"><td className="p-3">{row.reference}<div>{row.kind}</div></td><td className="p-3">{row.date ?? "Missing date"}</td><td className="p-3">{row.legalEntity}</td><td className="p-3">{money(row.net, row.currency)}</td><td className="p-3">{money(row.vat, row.currency)}</td><td className="p-3">{money(row.gross, row.currency)}</td><td className="p-3">{row.included ? "Included" : `Excluded: ${row.exclusion}`}</td></tr>)}</tbody></table></div>{!data.rows.length && <p>No documents in this period.</p>}</>}</section>;
}
