"use client";
import { useCallback, useEffect, useState } from "react";
type Conversion = { id: string; orderUnit: string; stockUnit: string; stockPerOrderUnit: string; status: string; reason: string; createdBy: string; reviewedBy: string | null };
const inputClass = "min-w-0 rounded-md border border-outline-variant/20 bg-surface-container px-3 py-2 text-sm";
const buttonClass = "rounded-md bg-primary/15 px-3 py-2 text-sm text-primary disabled:opacity-40";
export function InventoryUnitConversions({ itemId, stockUnit }: { itemId: string; stockUnit: string }) {
  const [data, setData] = useState<{ rows: Conversion[]; canPropose: boolean; canReview: boolean } | null>(null), [error, setError] = useState(""), [busy, setBusy] = useState(false), [review, setReview] = useState<{ id: string; action: string } | null>(null);
  const endpoint = `/api/v1/inventory/${itemId}/unit-conversions`;
  const load = useCallback(async () => { const response = await fetch(endpoint); const result = await response.json(); if (!response.ok) throw new Error(result.error?.message ?? "Could not load conversions."); setData(result.data); }, [endpoint]);
  useEffect(() => { setData(null); setReview(null); setError(""); void load().catch(e => setError(e.message)); }, [load]);
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const form = event.currentTarget, values = Object.fromEntries(new FormData(form)); setBusy(true); setError(""); try { const response = await fetch(endpoint, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(review ? { ...review, reason: values.reason } : { action: "propose", ...values, factor: Number(values.factor) }) }); const result = await response.json(); if (!response.ok) throw new Error(result.error?.message ?? "Conversion review failed."); setReview(null); form.reset(); await load(); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }
  return <section className="space-y-3 rounded-lg border border-outline-variant/15 p-4"><h3 className="font-semibold">Reviewed unit conversions</h3><p className="text-sm text-on-surface-variant">Define stock units ({stockUnit}) per order unit for this item. A reviewer must approve each ratio before use. Existing reservations and receipt drafts retain their original ratio when a conversion is revoked.</p>{error && <p role="alert" className="text-sm text-error">{error}</p>}{data?.rows.map(row => <div key={row.id} className="space-y-2 border-t border-outline-variant/15 pt-3"><p className="text-sm">1 {row.orderUnit} = {Number(row.stockPerOrderUnit)} {row.stockUnit} · <strong>{row.status}</strong></p><p className="whitespace-pre-wrap text-sm text-on-surface-variant">{row.reason}</p><p className="text-sm text-on-surface-variant">Proposed by {row.createdBy}{row.reviewedBy && ` · last reviewed by ${row.reviewedBy}`}</p><div className="flex gap-2">{row.status === "Pending" && <button disabled={!data.canReview || busy} className={buttonClass} onClick={() => setReview({ id: row.id, action: "approve" })}>Review approval</button>}{row.status !== "Revoked" && <button disabled={!data.canReview || busy} className={buttonClass} onClick={() => setReview({ id: row.id, action: "revoke" })}>Revoke</button>}</div></div>)}{data?.rows.length === 0 && <p className="text-sm">No reviewed conversions. Matching units use a ratio of 1.</p>}{data && (data.canPropose || review) && <form key={review?.id ?? "propose"} onSubmit={submit} className="grid gap-3"><h4 className="text-sm font-semibold">{review ? `${review.action === "approve" ? "Approve" : "Revoke"} selected conversion` : "Propose a conversion"}</h4>{!review && <div className="grid gap-3 sm:grid-cols-2"><label className="grid gap-1 text-sm">Order unit<input name="orderUnit" required maxLength={30} placeholder="BOX" className={inputClass} /></label><label className="grid gap-1 text-sm">{stockUnit} per order unit<input name="factor" type="number" required min="0.000001" max="1000000" step="0.000001" placeholder="12" className={inputClass} /></label></div>}<label className="grid gap-1 text-sm">Supplier specification / review reason<input name="reason" minLength={5} maxLength={1000} required className={inputClass} /></label><div className="flex gap-3"><button className={buttonClass} disabled={busy}>{busy ? "Saving…" : review ? "Confirm review" : "Save proposal"}</button>{review && <button type="button" className={buttonClass} onClick={() => setReview(null)}>Cancel</button>}</div></form>}</section>;
}
